language: c

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - texlive
      - wget
      - curl
      - sed
      - grep

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

cache:
  directories:
    - $HOME/.cache/latex

matrix:
 include:
   - env: LATEXMK="yes"
     addons:
       apt:
         packages:
           - latexmk
           - texlive
           - wget
           - curl
           - sed
           - grep

install:
 - test -z "$LATEXMK" || which latexmk
 - mkdir -p "$HOME"/.cache/latex
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/comment/comment.sty
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/misc/nextpage.sty
 - wget --tries=3 http://mirrors.ctan.org/fonts/stmaryrd.zip
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/wallpaper/wallpaper.sty
 - wget --tries=3 http://mirrors.ctan.org/macros/generic/xstring/xstring.sty
 - wget --tries=3 http://mirrors.ctan.org/macros/generic/xstring/xstring.tex
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/enumitem/enumitem.sty
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/mathtools.zip
 - wget --tries=3 http://mirrors.ctan.org/macros/generic/diagrams/xypic.zip
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/etoolbox/etoolbox.def
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/etoolbox/etoolbox.sty
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/titlesec.zip
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/braket/braket.sty
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/supertabular/supertabular.dtx http://mirrors.ctan.org/macros/latex/contrib/supertabular/supertabular.ins
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/soul/soul.dtx http://mirrors.ctan.org/macros/latex/contrib/soul/soul.ins
 - wget --tries=3 http://mirrors.ctan.org/macros/latex/contrib/xcolor/xcolor.dtx http://mirrors.ctan.org/macros/latex/contrib/xcolor/xcolor.ins
 - wget --tries=3 http://mirrors.ctan.org/graphics/pgf/base.zip
 - cp "$HOME"/.cache/latex/* ./
 - unzip stmaryrd && mv stmaryrd/*.{mf,dtx} ./ && latex stmaryrd.dtx
 - unzip mathtools.zip && (cd mathtools && for i in *.dtx; do (mv $i ../ && cd .. && tex $i); done)
 - unzip xypic.zip && mv xypic/*/* ./
 - unzip titlesec.zip && mv titlesec/*.{tss,sty,def} ./
 - latex supertabular.ins
 - latex soul.ins
 - latex xcolor.ins
 - unzip base && find base -name "*.sty" -o -name "*.tex" -o -name "*.def" -o -name "*.cfg" | grep -v pgfmanual | xargs cp -t ./

script:
  # gitinfo2 setup... :S
  - wget https://raw.githubusercontent.com/Hightor/gitinfo2/CTAN/gitinfo2.sty
  - wget https://raw.githubusercontent.com/Hightor/gitinfo2/CTAN/gitexinfo.sty
  - pwd
  - cd .git/hooks
  - wget https://gist.githubusercontent.com/jonaprieto/607fea82f55dba1945ddfcd7248905c3/raw/1b3df605071f16b7a5167efe7923c284cb26dd1c/post-commit
  - cp post-commit post-merge
  - cp post-commit post-checkout
  - sudo chmod +x post-commit post-merge post-checkout
  - cd ..
  - cd ..
  - git init
  - git checkout -b travis-test
  - pwd
  - wget https://raw.githubusercontent.com/simhu/cubic/master/mathpartir.sty
  - make
